DROP DATABASE COLLEGEUPDATES;

CREATE DATABASE COLLEGEUPDATES;

USE COLLEGEUPDATES;

DROP TABLE DEPARTMENT;

CREATE TABLE DEPARTMENT (
    DEPARTMENT_NAME VARCHAR(50) PRIMARY KEY,
    HEAD_OF_DEPARTMENT VARCHAR(50)
);

INSERT INTO DEPARTMENT VALUES('COMPUTER SCIENCE','R. K. GUPTA');

DROP TABLE USER;

CREATE TABLE USER (
    USER_ID VARCHAR(30) PRIMARY KEY,
    USER_NAME VARCHAR(50) NOT NULL,
    GENDER CHAR(1) NOT NULL,
    DATE_OF_BIRTH DATE NOT NULL,
    BRANCH VARCHAR(30) NOT NULL,
    DEPARTMENT_NAME VARCHAR(50) NOT NULL,
    EMAIL_ID VARCHAR(50) UNIQUE NOT NULL,
    MOBILE_NUMBER BIGINT(10) UNIQUE NOT NULL,
    PROFILE_PIC BLOB,
    USER_TYPE CHAR(1) NOT NULL,
    FOREIGN KEY (DEPARTMENT_NAME) REFERENCES DEPARTMENT(DEPARTMENT_NAME)
);

INSERT INTO USER VALUES('0901CS111029','HITENDRA GARG','M','1992-05-26','CSE','COMPUTER SCIENCE','HITENDRAGARG001@GMAIL.COM',9620339100,NULL,'E');

SELECT `user`.`USER_ID`,
    `user`.`USER_NAME`,
    `user`.`PASSWORD`,
    `user`.`GENDER`,
    `user`.`DATE_OF_BIRTH`,
    `user`.`BRANCH`,
    `user`.`DEPARTMENT_NAME`,
    `user`.`EMAIL_ID`,
    `user`.`MOBILE_NUMBER`,
    `user`.`PROFILE_PIC`,
    `user`.`USER_TYPE`
FROM `collegeupdates`.`user`;

DROP TABLE USER_POST;

CREATE TABLE USER_POST (
    POST_ID BIGINT(10) PRIMARY KEY AUTO_INCREMENT,
    POST_OWNER_ID VARCHAR(30),
    POST_DATE_TIME DATETIME NOT NULL,
    POST_TEXT VARCHAR(500),
    POST_IMAGE1 BLOB,
    POST_IMAGE2 BLOB,
    POST_IMAGE3 BLOB,
    POST_IMAGE4 BLOB,
    NO_OF_LIKES BIGINT(5),
    FOREIGN KEY (POST_OWNER_ID) REFERENCES USER(USER_ID)
);

SELECT `user_post`.`POST_ID`,
    `user_post`.`POST_OWNER_ID`,
    `user_post`.`POST_DATE_TIME`,
    `user_post`.`POST_TEXT`,
    `user_post`.`POST_IMAGE1`,
    `user_post`.`POST_IMAGE2`,
    `user_post`.`POST_IMAGE3`,
    `user_post`.`POST_IMAGE4`,
    `user_post`.`NO_OF_LIKES`
FROM `collegeupdates`.`user_post`;


DROP TABLE USER_LIKED_POST;

CREATE TABLE USER_LIKED_POST (
    POST_ID BIGINT(10),
    USER_ID VARCHAR(30),
    FOREIGN KEY (POST_ID) REFERENCES USER_POST(POST_ID),
    FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID),
    PRIMARY KEY (POST_ID,USER_ID)
);

SELECT `user_liked_post`.`POST_ID`,
    `user_liked_post`.`USER_ID`
FROM `collegeupdates`.`user_liked_post`;


DROP TABLE COMMENTS_ON_POST;

CREATE TABLE COMMENTS_ON_POST (
    POST_ID BIGINT(10),
    COMMENT_BY_USER_ID VARCHAR(30),
    COMMENT_DATE_TIME DATETIME NOT NULL,
    COMMENT_TEXT VARCHAR(500),
    COMMENT_IMAGE BLOB,
    FOREIGN KEY (POST_ID) REFERENCES USER_POST(POST_ID),
    FOREIGN KEY (COMMENT_BY_USER_ID) REFERENCES USER(USER_ID)
);

SELECT `comments_on_post`.`POST_ID`,
    `comments_on_post`.`COMMENT_BY_USER_ID`,
    `comments_on_post`.`COMMENT_DATE_TIME`,
    `comments_on_post`.`COMMENT_TEXT`,
    `comments_on_post`.`COMMENT_IMAGE`
FROM `collegeupdates`.`comments_on_post`;

COMMIT;



UPDATE user_post
SET
NO_OF_LIKES = NO_OF_LIKES+1
WHERE POST_ID = 1;
